### PR TITLE
avoid string to cstring conversion

### PR DESCRIPTION
**Pull request by narimiran**
supersedes #45

### CODE REVIEW

**Comment by tersec** [comment]
How is this better?

**Comment by narimiran** [comment]
> How is this better?

Because currently the compiler complains about implicit `string` -> `cstring` conversion for `deserializedType`.

And if one field was recently changed from `cstring` to `string` (https://github.com/status-im/nim-json-serialization/commit/5034fef8d048d8d9e5e0228864dacf627d35b96f), why not the other?

**Comment by tersec** [comment]
Yes, I mean how is it better than https://github.com/status-im/nim-json-serialization/pull/45, which also fixes this implicit `string` -> `cstring` conversion warning?

One field has contents which have to be dynamically constructed at runtime. The other selects from some pre-existing fields (pointers) in a string constant pool of type names all known in advance at compile time, and avoids any possibility of heap allocation, just does pointer copies. No reason to make the latter field a `string` just because the former has to be.

**Comment by narimiran** [comment]
> I mean how is it better than https://github.com/status-im/nim-json-serialization/pull/45, which also fixes this implicit string -> cstring conversion warning?

Hmmm, but it doesn't?

`typeName` is `typetraits.name(T)`, which is a `string`. And `deserializedType` is a `cstring` (before this PR and still in your PR).

**Comment by tersec** [comment]
Have you tried it? It does remove this `CStringConv` warning.

Specifically, it's
```nim
const typeName = typetraits.name(T)
```
It's a compile-time constant, so effectively a `static[string]`. Typewise, it's no different than if it were
```nim
const typeName = "some string"
```
which would also be safe for `cstring` "conversion" for the same reason, as documented by https://nim-lang.org/docs/manual.html#types-cstring-type
> Certain idioms like conversion of a `const` string to `cstring` are safe and will remain to be allowed.

For example,
```nim
import std/typetraits

proc f(s: cstring) = echo s

const typeName = typetraits.name(int)
f(typeName)
```
compiles fine, without warnings.

**Pull request closed without merging**
